### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

# This will create this metric in a specific component so that the same
# custom metric name will be distinct under different applications
# see: https://community.appdynamics.com/t5/Knowledge-Base/How-to-troubleshoot-missing-custom-metrics-or-extensions-metrics/ta-p/28695
metricPrefix: "Server|Component:<Component_id>|Custom Metrics|Solace|"

# List of Solace Servers
servers:
  - mgmtUrl: "http://localhost:8080/SEMP"
    adminUser: "admin"
    password: "admin"
    # encryptedPassword: "gD1962YptbA8bsaHmYXlSw=="
    # encryptionKey: "na1jFUKT8euDXp1p7bgwIxhI6ZESLylz"
    #displayName is required. Displays your server name in metric path.
    displayName: "PrimaryVMR"
    # requestTimeout: 1000000 # one second timeout
    vpnExclusionPolicy: "blacklist"
    excludeMsgVpns: ["#config-sync", "default"]
    queueExclusionPolicy: "blacklist"
    excludeQueues: ["#P2P/.*"]
    topicEndpointExclusionPolicy: "blacklist"
    excludeTopicEndpoints: ["#P2P/.*"]
    excludeTemporaries: true

# number of concurrent tasks
numberOfThreads: 2

# timeout for the thread
# threadTimeout: 30
